lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: 'org.wso2.choreo.connect.enforcer<type=ExtAuthMetrics><>total_request_count: (.*)'
    name: org_wso2_choreo_connect_enforcer_request_count_total
    help: "WSO2 choreo connect enforcer total request count."
    attrNameSnakeCase: true
    type: COUNTER
  - pattern: 'org.wso2.choreo.connect.enforcer<type=ExtAuthMetrics><>(average_response_time_millis|max_response_time_millis|min_response_time_millis|request_count_in_last_five_minute_window|request_count_window_start_time_millis): (.*)'
    name: org_wso2_choreo_connect_enforcer_$1
    help: "WSO2 choreo connect enforcer $1."
    attrNameSnakeCase: true
    type: GAUGE
  - pattern: 'org.wso2.choreo.connect.enforcer<type=ThreadPoolConfig><>(\w+): (.*)'
    name: org_wso2_choreo_connect_enforcer_thread_pool_$1
    help: "WSO2 choreo connect enforcer thread pool $1."
    attrNameSnakeCase: true
    type: GAUGE
  - pattern: 'java.lang<type=OperatingSystem><>(\w+): (.*)'
    name: os_$1
    help: Operating System $1
    attrNameSnakeCase: true
    type: GAUGE